package td1;


/**
* td1/GestionSallesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Thomas/eclipse-workspace/TP_Service_Salles_Corba/src/td1.idl
* jeudi 28 mai 2020 17 h 25 CEST
*/

public abstract class GestionSallesPOA extends org.omg.PortableServer.Servant
 implements td1.GestionSallesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ajouterSalle", new java.lang.Integer (0));
    _methods.put ("salleExiste", new java.lang.Integer (1));
    _methods.put ("capaciteSalle", new java.lang.Integer (2));
    _methods.put ("disponibiliteSalle", new java.lang.Integer (3));
    _methods.put ("placerPersonne", new java.lang.Integer (4));
    _methods.put ("placerPersonneDansSalle", new java.lang.Integer (5));
    _methods.put ("salleAttribuee", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // td1/GestionSalles/ajouterSalle
       {
         String nomSalle = in.read_string ();
         int nbPlaces = in.read_long ();
         boolean $result = false;
         $result = this.ajouterSalle (nomSalle, nbPlaces);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // td1/GestionSalles/salleExiste
       {
         String nomSalle = in.read_string ();
         boolean $result = false;
         $result = this.salleExiste (nomSalle);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // td1/GestionSalles/capaciteSalle
       {
         String nomSalle = in.read_string ();
         int $result = (int)0;
         $result = this.capaciteSalle (nomSalle);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // td1/GestionSalles/disponibiliteSalle
       {
         String nomSalle = in.read_string ();
         int $result = (int)0;
         $result = this.disponibiliteSalle (nomSalle);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // td1/GestionSalles/placerPersonne
       {
         String nomPersonne = in.read_string ();
         String $result = null;
         $result = this.placerPersonne (nomPersonne);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // td1/GestionSalles/placerPersonneDansSalle
       {
         String nomSalle = in.read_string ();
         String nomPersonne = in.read_string ();
         boolean $result = false;
         $result = this.placerPersonneDansSalle (nomSalle, nomPersonne);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // td1/GestionSalles/salleAttribuee
       {
         String nomPersonne = in.read_string ();
         String $result = null;
         $result = this.salleAttribuee (nomPersonne);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:td1/GestionSalles:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionSalles _this() 
  {
    return GestionSallesHelper.narrow(
    super._this_object());
  }

  public GestionSalles _this(org.omg.CORBA.ORB orb) 
  {
    return GestionSallesHelper.narrow(
    super._this_object(orb));
  }


} // class GestionSallesPOA
