package td1;


/**
* td1/GestionSallesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Thomas/eclipse-workspace/TP_Service_Salles_Corba/src/td1.idl
* jeudi 28 mai 2020 17 h 25 CEST
*/

public interface GestionSallesOperations 
{
  boolean ajouterSalle (String nomSalle, int nbPlaces);
  boolean salleExiste (String nomSalle);
  int capaciteSalle (String nomSalle);
  int disponibiliteSalle (String nomSalle);
  String placerPersonne (String nomPersonne);
  boolean placerPersonneDansSalle (String nomSalle, String nomPersonne);
  String salleAttribuee (String nomPersonne);
} // interface GestionSallesOperations
