package td1;

/**
* td1/GestionSallesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Thomas/eclipse-workspace/TP_Service_Salles_Corba/src/td1.idl
* jeudi 28 mai 2020 17 h 25 CEST
*/

public final class GestionSallesHolder implements org.omg.CORBA.portable.Streamable
{
  public td1.GestionSalles value = null;

  public GestionSallesHolder ()
  {
  }

  public GestionSallesHolder (td1.GestionSalles initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = td1.GestionSallesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    td1.GestionSallesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return td1.GestionSallesHelper.type ();
  }

}
