package td1;


/**
* td1/GestionSalles.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Thomas/eclipse-workspace/TP_Service_Salles_Corba/src/td1.idl
* jeudi 28 mai 2020 17 h 25 CEST
*/

public interface GestionSalles extends GestionSallesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionSalles
